name: voxone
description: TBD

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.0

environment:
  sdk: ^3.3.0

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^6.0.0
  collection: ^1.18.0
  dart_extensions_methods: ^2.0.0
  dart_minilog: ^0.0.2
  flame: ^1.18.0
  flame_audio: ^2.10.2
  flutter_animate: ^4.5.0
  get: ^4.6.6
  kart: ^1.0.8
  kt_dart: ^1.1.0
  list_operators: ^0.5.0
  mp_audio_stream: ^0.1.5
  rxdart: ^0.27.7
  stream_transform: ^2.1.0
  supercharged: ^2.1.1
  shared_preferences: ^2.2.3
  flutter_soloud: ^2.0.2
  flame_forge2d: ^0.18.1
  flame_tiled: ^1.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  test: ^1.24.9

flutter:
  assets:
    - assets/audio/
    - assets/audio/sound/
    - assets/fonts/
    - assets/images/
    - assets/images/fonts/
    - assets/images/entities/
  shaders:
    - assets/shaders/checkerboard.frag
    - assets/shaders/explosion.frag
    - assets/shaders/ground.frag
    - assets/shaders/hex_shield.frag
    - assets/shaders/noise.frag
    - assets/shaders/plasma_shield.frag
    - assets/shaders/space.frag
    - assets/shaders/voxel.frag
